//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanguo.Core.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLiteCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLiteCommands() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanguo.Core.Data.SQLiteCommands", typeof(SQLiteCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO USERS VALUES({0},&quot;{1}&quot;,&quot;{2}&quot;,{3},&quot;{4}&quot;); 的本地化字符串。
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE PROPERTIES(
        ///ID INT PRIMARY KEY NOT NULL,
        ///PROPERTYNAME TEXT NOT NULL,
        ///PROPERTYVALUE TEXT NOT NULL
        ///); 的本地化字符串。
        /// </summary>
        public static string CreatePropertiesTable {
            get {
                return ResourceManager.GetString("CreatePropertiesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE USERS(
        ///ID INT PRIMARY KEY NOT NULL,
        ///USERNAME TEXT NOT NULL,
        ///ENCRYPTEDPW TEXT NOT NULL,
        ///SCORE INT NOT NULL,
        ///AVATAR TEXT NOT NULL
        ///); 的本地化字符串。
        /// </summary>
        public static string CreateUserTable {
            get {
                return ResourceManager.GetString("CreateUserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM PROPERTIES; 的本地化字符串。
        /// </summary>
        public static string SelectProperty {
            get {
                return ResourceManager.GetString("SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM USERS; 的本地化字符串。
        /// </summary>
        public static string SelectUsers {
            get {
                return ResourceManager.GetString("SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM USERS WHERE USERNAME = &quot;{0}&quot;; 的本地化字符串。
        /// </summary>
        public static string UsernameQuery {
            get {
                return ResourceManager.GetString("UsernameQuery", resourceCulture);
            }
        }
    }
}
